generate_model_catalog.py doesn't use viewser anymore

diff --git a/.github/workflows/check_if_new_model_added.yml b/.github/workflows/check_if_new_model_added.yml
--- a/.github/workflows/check_if_new_model_added.yml
+++ b/.github/workflows/check_if_new_model_added.yml
@@ -45,6 +45,10 @@ jobs:
           echo $removed_dirs
           if [ -n "$new_dirs" ] || [ -n "$removed_dirs" ]; then
             python documentation/catalogs/generate_model_catalog.py  
+            if [ $? -ne 0 ]; then
+              echo "Generating catalogs failed."
+              exit 1
+            fi
             echo "Model catalog is updated."           
           else
             echo "No new or removed folders detected."
